SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

LINE_WIDTH = 2
SHOT_RADIUS = 5
EXPLOSION_PARTICLES = 10
EXPLOSION_PARTICLE_SIZE = 1


# Player constants
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_DEFAULT_SPEED = 200
PLAYER_MAX_SPEED = 500
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_LIVES = 4

# Asteroid constants
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MIN_POINTS = 20
ASTEROID_MAX_POINTS = 100